name: 6th Sense
favicon: null
layout_spectrum: 0.9158519669435918
typography_spectrum: 0.9637985827866942
title: 6th Sense Paranormal Investigations
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4017735153902322
  lightness: 0.06856769928708673
  saturation: 0.20658138464204967
  rhythmicContrast: 0.5388245577923954
purpose: []
